In [2]:
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [83]:
df = pd.read_csv("/Users/ivanbersenev/Documents/code/python/VKDATAML/ikit.csv")
df = df.drop(['Unnamed: 0', 'home_town'], axis = 1)
df.columns = ["Имя", "Дата рождения","Город", "Пол", "Графовая группа", "Количество связей", "Центральность","Соеденительная центральность", "Близостная центральность", "Посредническая центральность", "Ранжированная центральность", "Идентификатор"]
df["Пол"] = np.where(df["Пол"] == 1, "Ж", "М")
for column in ["Центральность","Соеденительная центральность", "Близостная центральность", "Посредническая центральность", "Ранжированная центральность"]: 
    df[column] = round((df[column] - df[column].min()) / (df[column].max() - df[column].min()), 2)
# df['birthday'] = pd.to_datetime(df.bdate, errors="coerce")
# df['birthday_month'] = df.birthday.dt.month
# df['birthday_year'] = df.birthday.dt.year

In [90]:
# df.head(5)
styles = [{
    'selector': 'th',
    'props': [('text-align', 'left')]
}]

categorical_columns = df.select_dtypes(['object']).columns
for col in categorical_columns:
    styles.append({'selector': f'[data-columns="{col}"]', 'props': [('text-align', 'left')]})

def align_text(x):
    if isinstance(x, str):
        return 'text-align: left'
    else:
        return 'text-align: right'


styled_df = df.style.set_table_styles(styles)
styled_df = df.style.format('{:.2f}').applymap(align_text, subset=pd.IndexSlice[:, :])

styled_df

/var/folders/mq/6jjr20h17tdb5hd1gx2p2hcm0000gn/T/ipykernel_9757/2034302854.py:19: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_df = df.style.format('{:.2f}').applymap(align_text, subset=pd.IndexSlice[:, :])

ValueError: Unknown format code 'f' for object of type 'str'

In [10]:
# сортировка по degree
df.sort_values(by = "Количество связей", ascending=False).head(5)

,Имя,Дата рождения,Город,Пол,Графовая группа,Количество связей,Центральность,Соеденительная центральность,Близостная центральность,Посредническая центральность,Ранжированная центральность,Идентификатор
230,Lyubov Makukha,10.3.1979,NaN,Ж,333,523,1.000000,1.000000,1.000000,0.929433,1.000000,392573443
192,Alexey Gubanov,17.10.2002,Zheleznogorsk,М,333,381,0.728489,0.484111,0.979745,1.000000,0.648349,166813245
225,Vitaly Vaynshteyn,26.7,Krasnoyarsk,М,333,350,0.669216,0.539344,0.961386,0.696349,0.666527,273684138
5,Ruslan Brezhnev,NaN,Krasnoyarsk,М,2,231,0.441683,0.234927,0.891053,0.389577,0.436166,7382377
244,Tilekbek Tashbaev,26.12,NaN,М,139,224,0.428298,0.154377,0.915432,0.708506,0.349761,224381850

In [11]:
df.sort_values(by = "Посредническая центральность", ascending=False).head(5)

,Имя,Дата рождения,Город,Пол,Графовая группа,Количество связей,Центральность,Соеденительная центральность,Близостная центральность,Посредническая центральность,Ранжированная центральность,Идентификатор
192,Alexey Gubanov,17.10.2002,Zheleznogorsk,М,333,381,0.728489,0.484111,0.979745,1.000000,0.648349,166813245
230,Lyubov Makukha,10.3.1979,NaN,Ж,333,523,1.000000,1.000000,1.000000,0.929433,1.000000,392573443
403,Vasily Nikonov,NaN,Sayanogorsk,М,9,222,0.424474,0.197033,0.935876,0.711310,0.373266,277634207
244,Tilekbek Tashbaev,26.12,NaN,М,139,224,0.428298,0.154377,0.915432,0.708506,0.349761,224381850
225,Vitaly Vaynshteyn,26.7,Krasnoyarsk,М,333,350,0.669216,0.539344,0.961386,0.696349,0.666527,273684138

In [13]:
df[df['Пол'] == "М"].head(5)

,Имя,Дата рождения,Город,Пол,Графовая группа,Количество связей,Центральность,Соеденительная центральность,Близостная центральность,Посредническая центральность,Ранжированная центральность,Идентификатор
4,Denis Kustov,NaN,Krasnoyarsk,М,2,73,0.139579,0.028882,0.847942,0.270974,0.129391,4829157
5,Ruslan Brezhnev,NaN,Krasnoyarsk,М,2,231,0.441683,0.234927,0.891053,0.389577,0.436166,7382377
9,Andrey Kushnarenko,28.7.1978,Krasnoyarsk,М,2,170,0.325048,0.155260,0.878750,0.381465,0.295794,90694585
13,Petr Dyachuk,29.3,Krasnoyarsk,М,2,49,0.093690,0.017962,0.828116,0.177905,0.086162,324960170
14,Kubanychbek Kamchybekov,5.6.2003,Krasnoyarsk,М,139,87,0.166348,0.015935,0.798811,0.227657,0.134109,674207746

In [20]:
def formatting(val):
    color = 'red' if val < 100 else 'black'
    return f'color: {color}'

df.head(10).style.map(formatting, subset = ["Количество связей"])

In [19]:
df.sort_values(by="Центральность", ascending=False).head(5)

,Имя,Дата рождения,Город,Пол,Графовая группа,Количество связей,Центральность,Соеденительная центральность,Близостная центральность,Посредническая центральность,Ранжированная центральность,Идентификатор
230,Lyubov Makukha,10.3.1979,NaN,Ж,333,523,1.000000,1.000000,1.000000,0.929433,1.000000,392573443
192,Alexey Gubanov,17.10.2002,Zheleznogorsk,М,333,381,0.728489,0.484111,0.979745,1.000000,0.648349,166813245
225,Vitaly Vaynshteyn,26.7,Krasnoyarsk,М,333,350,0.669216,0.539344,0.961386,0.696349,0.666527,273684138
5,Ruslan Brezhnev,NaN,Krasnoyarsk,М,2,231,0.441683,0.234927,0.891053,0.389577,0.436166,7382377
244,Tilekbek Tashbaev,26.12,NaN,М,139,224,0.428298,0.154377,0.915432,0.708506,0.349761,224381850

In [25]:
# Форматирование цвета ячеек по их величине
max_value = df['Количество связей'].max()
def formatting(val):
    ratio = val / max_value
    r = int( max(0, min(255, 255 * (1 - ratio))))
    g = int(max(0, min(255, 255 * ratio)))
    color = f'rgba({r},{g},0,1)'
    return f'color: {color}'

df.sort_values(by="Количество связей", ascending = False).head(10).style.map(formatting, subset = ["Количество связей"])

In [32]:
description = df.describe()

new_index_names = {
    'count': 'Количество',
    'mean': 'Среднее',
    'std': 'Стандартное отклонение',
    'min': 'Минимальное значение',
    '25%': '25-й процентиль',
    '50%': '50-й процентиль',
    '75%': '75-й процентиль',
    'max': 'Максимальное значение'
}
description = description.rename(index=new_index_names)
description

,Графовая группа,Количество связей,Центральность,Соеденительная центральность,Близостная центральность,Посредническая центральность,Ранжированная центральность,Идентификатор
Количество,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03
Среднее,311.638400,13.108000,0.025063,0.003901,0.504246,0.028771,0.024975,2.979998e+08
Стандартное отклонение,261.788594,22.672325,0.043351,0.021634,0.283130,0.061856,0.040073,1.792090e+08
Минимальное значение,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.963980e+05
25-й процентиль,10.000000,1.000000,0.001912,0.000000,0.479203,0.000083,0.002189,1.590053e+08
50-й процентиль,317.000000,6.000000,0.011472,0.000196,0.625855,0.007688,0.014301,2.771760e+08
75-й процентиль,465.000000,17.000000,0.032505,0.002480,0.693668,0.030404,0.032217,4.268579e+08
Максимальное значение,1115.000000,523.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.437004e+08

In [46]:
cities_df = df.groupby(['Город']).aggregate({"Имя":"count"}).reset_index()
cities_df.columns = ["Город", "Количество пользователей"]
cities_df.head(10)

         Город  Количество пользователей
0       Abakan                        44
1       Abalak                         1
2         Aban                         2
3        Abaza                         1
4      Achinsk                        28
5  Addis Ababa                         1
6     Aginskoe                         3
7       Aktobe                         1
8  Alexandrovo                         1
9       Almaty                        13

In [52]:
df_pupils = df.groupby(['Город','Пол']).agg(['count'])['Идентификатор'].reset_index()
df_pupils.columns = ['Город', "Пол", "Количество пользователей"]
df_pupils

                     Город Пол  Количество пользователей
0                   Abakan   Ж                        24
1                   Abakan   М                        20
2                   Abalak   М                         1
3                     Aban   Ж                         1
4                     Aban   М                         1
..                     ...  ..                       ...
401  Zheleznogorsk-Ilimsky   М                         1
402               Zhitomir   Ж                         1
403                Zhovkva   М                         1
404               İstanbul   М                         1
405                  Ōsaka   М                         1

[406 rows x 3 columns]

In [58]:
df_sexs = df.groupby(["Пол"]).agg(['count'])['Идентификатор'].reset_index()
df_sexs.columns = ["Пол", "Количество пользователей"]
df_sexs

  Пол  Количество пользователей
0   Ж                      2003
1   М                      2997

In [69]:
df.groupby(["Графовая группа", "Имя"]).agg(['count'])['Идентификатор'].drop("count", axis = 1)

Empty DataFrame
Columns: []
Index: [(0, Olga Berestyuk), (1, Stanislav Alyokminsky), (2, Abdulmalik Akhmedov), (2, Agnessa Pogosyan), (2, Akmal Jumaev), (2, Alesya Korovina), (2, Alexander Bausk), (2, Alexander Bochegov), (2, Alexander Eryomin), (2, Alexander Gataullin), (2, Alexander Kirillov), (2, Alexander Klykov), (2, Alexander Kolomytsev), (2, Alexander Korolyov), (2, Alexander Kurzenkov), (2, Alexander Kuzmin), (2, Alexander Legalov), (2, Alexander Merkulov), (2, Alexander Mostovskikh), (2, Alexander Neyman), (2, Alexander Novoselov), (2, Alexander Pogrebnikov), (2, Alexander Rakhmanov), (2, Alexander Rashenko), (2, Alexander Shagin), (2, Alexander Shevchenko), (2, Alexander Solodyankin), (2, Alexander Timofeev), (2, Alexander Tolstov), (2, Alexander Ukolov), (2, Alexander Unterberg), (2, Alexander Vasilyev), (2, Alexandra Dvorinovich), (2, Alexandra Gantimurova), (2, Alexandra Matuzko), (2, Alexandra Molokanova), (2, Alexandra Nazhmudinova), (2, Alexandra Ponomareva), (2, Alexey Antipin), (2, Alexey Arsenyev), (2, Alexey Bobrov), (2, Alexey Bogomolov), (2, Alexey Cherednichenko), (2, Alexey Dudaev), (2, Alexey Ivanov), (2, Alexey Kovalenko), (2, Alexey Mikachev), (2, Alexey Muzhaylo), (2, Alexey Panov), (2, Alexey Pavlov), (2, Alexey Pesterev), (2, Alexey Piskunov), (2, Alexey Pnev), (2, Alexey Pryazhnikov), (2, Alexey Rossiev), (2, Alexey Safonov), (2, Alexey Sknar), (2, Alexey Sleptsov), (2, Alexey Teteryatnikov), (2, Alexey Timakov), (2, Alexey Vyvdenko), (2, Alexey Yablonsky), (2, Alexey Yanin), (2, Alexey Zmienko), (2, Alina Gavrilova), (2, Alina Leskovskaya), (2, Alina Polozova), (2, Alina Reshetnikova), (2, Alina Runova), (2, Alina Saprykina), (2, Alina Shmidt), (2, Alina Slesareva), (2, Alina Titova), (2, Alisa Sharafeeva), (2, Alisa Shmagly), (2, Altana Budazhapova), (2, Alyona Buyankina), (2, Alyona Kazakevich), (2, Alyona Manko), (2, Alyona Potapova), (2, Aman Bayke), (2, Amar Dasheev), (2, Amir Abdurashidzoda), (2, Amir Khalikov), (2, Anastasia Anisimova), (2, Anastasia Basargina), (2, Anastasia Bolotova), (2, Anastasia Ereschenko), (2, Anastasia Goponenko), (2, Anastasia Katsunova), (2, Anastasia Kornienko), (2, Anastasia Kozlova), (2, Anastasia Kuznetsova), (2, Anastasia Lapa), (2, Anastasia Larionova), (2, Anastasia Leonenkova), (2, Anastasia Lopushenko), (2, Anastasia Lukina), (2, Anastasia Nikitina), (2, Anastasia Raskina), ...]

[4990 rows x 0 columns]